# Generated by Django 3.0.2 on 2020-01-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transactions',
            field=models.TextField(default=''),
        ),
    ]
