# Generated by Django 3.0.2 on 2020-01-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
