# Generated by Django 3.0.2 on 2020-01-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
